"""
HTML/CSS/JS Syntax Fixer for LLM-generated code.

This module automatically fixes common syntax errors in HTML files
generated by LLMs, particularly the "missing space" issue that occurs
frequently when LLMs generate minified or compressed code.

Common fixes:
- CSS: viewBox='00512512' → viewBox='0 0 512 512'
- CSS: padding:14px0 → padding:14px 0
- CSS: background:00 → background:transparent
- CSS: background-size:256px256px → background-size:256px 256px
- JS: case0: → case 0: (switch statements)
- JS: ctx.font = '20052px' → ctx.font = '200 52px'
"""

import re
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field


@dataclass
class FixResult:
    """Result of HTML fixing operation."""
    original_content: str
    fixed_content: str
    fixes_applied: List[Dict[str, str]] = field(default_factory=list)
    has_changes: bool = False

    def to_dict(self) -> Dict:
        return {
            "has_changes": self.has_changes,
            "fixes_count": len(self.fixes_applied),
            "fixes": self.fixes_applied,
            "diff_summary": self._generate_diff_summary()
        }

    def _generate_diff_summary(self) -> str:
        if not self.fixes_applied:
            return "No changes needed"
        categories = {}
        for fix in self.fixes_applied:
            cat = fix.get("category", "other")
            categories[cat] = categories.get(cat, 0) + 1
        return ", ".join(f"{k}: {v}" for k, v in categories.items())


class HTMLFixer:
    """Fixes common syntax errors in LLM-generated HTML/CSS/JS code."""

    def __init__(self):
        self.fixers = [
            # Order matters - more specific patterns first
            self._fix_svg_viewbox,
            self._fix_css_background_size,
            self._fix_css_padding,
            self._fix_css_margin,
            self._fix_css_background_zero,
            self._fix_css_border_radius,
            self._fix_js_switch_case,
            self._fix_js_font_declaration,
            self._fix_css_generic_unit_values,
        ]

    def fix(self, content: str) -> FixResult:
        """
        Apply all fixers to the content.

        Args:
            content: The HTML content to fix

        Returns:
            FixResult with original, fixed content, and list of fixes applied
        """
        fixes = []
        current = content

        for fixer in self.fixers:
            fixed, applied_fixes = fixer(current)
            if applied_fixes:
                fixes.extend(applied_fixes)
                current = fixed

        return FixResult(
            original_content=content,
            fixed_content=current,
            fixes_applied=fixes,
            has_changes=len(fixes) > 0
        )

    def _fix_svg_viewbox(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix SVG viewBox missing spaces: viewBox='00512512' → viewBox='0 0 512 512'"""
        fixes = []

        # Pattern: viewBox='X' where X is digits without spaces
        def replace_viewbox(match):
            original = match.group(0)
            value = match.group(1)

            # Try to parse as 4 numbers without spaces
            # Common patterns: "00512512" should be "0 0 512 512"
            if len(value) >= 4 and value.isdigit():
                # Try to intelligently split
                # Common cases: 512x512, 256x256, 1024x768 etc.
                if len(value) == 8:
                    # Likely "0 0 WWWW HHHH" pattern
                    w = value[2:5]
                    h = value[5:8]
                    fixed = f"0 0 {w} {h}"
                elif len(value) == 7:
                    # Could be "0 0 WWW HHHH" or similar
                    w = value[2:5]
                    h = value[5:7]
                    fixed = f"0 0 {w} {h}"
                else:
                    # Fallback: add spaces every 1-3 chars based on common patterns
                    fixed = ' '.join([value[i:i+3] for i in range(0, len(value), 3)])

                fixes.append({
                    "category": "svg",
                    "type": "viewbox_spacing",
                    "original": original,
                    "fixed": f"viewBox='{fixed}'"
                })
                return f"viewBox='{fixed}'"
            return original

        # Match viewBox='digits' or viewBox="digits"
        pattern = r"viewBox=['\"](\d+)['\"]"
        result = re.sub(pattern, replace_viewbox, content, flags=re.IGNORECASE)

        return result, fixes

    def _fix_css_background_size(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix background-size missing space: 256px256px → 256px 256px"""
        fixes = []

        # Pattern: background-size:XXXpxYYYpx (no space between px values) → background-size:XXXpx YYYpx
        # Only match when there's NO space between the px values
        def replace_bg_size(match):
            original = match.group(0)
            values = match.group(1)

            # Check if already has proper spacing
            if re.match(r'^\d+px\s+\d+px', values):
                return original  # Already correct, no change

            # Parse values like "256px256px" (missing space)
            parts = re.findall(r'\d+px', values)
            if len(parts) >= 2:
                fixed = ' '.join(parts[:2])
                # Preserve any remaining content after the first two values
                consumed = ''.join(parts[:2])
                remaining = values[len(consumed):]
                if remaining:
                    fixed += remaining

                # Only report fix if something actually changed
                if fixed != values:
                    fixes.append({
                        "category": "css",
                        "type": "background_size_spacing",
                        "original": original,
                        "fixed": f"background-size:{fixed}"
                    })
                    return f"background-size:{fixed}"
            return original

        # Only match patterns where px values are adjacent (no space)
        pattern = r"background-size:(\d+px\d+px)"
        result = re.sub(pattern, replace_bg_size, content, flags=re.IGNORECASE)

        return result, fixes

    def _fix_css_padding(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix padding missing space: padding:14px0 → padding:14px 0"""
        fixes = []

        # Pattern: padding:XpxYpx or padding:Xpx0 → padding:Xpx Ypx or padding:Xpx 0
        def replace_padding(match):
            original = match.group(0)
            prop = match.group(1)  # padding or padding-top etc.
            values = match.group(2)

            fixed_values = self._fix_css_value_spacing(values, "px")

            if fixed_values != values:
                fixes.append({
                    "category": "css",
                    "type": "padding_spacing",
                    "original": original,
                    "fixed": f"{prop}:{fixed_values}"
                })
                return f"{prop}:{fixed_values}"
            return original

        # Match padding, padding-top, padding-bottom, etc.
        pattern = r"(padding(?:-top|-right|-bottom|-left)?):([^;}'\"]+)"
        result = re.sub(pattern, replace_padding, content, flags=re.IGNORECASE)

        return result, fixes

    def _fix_css_margin(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix margin missing space: margin:10px0 → margin:10px 0"""
        fixes = []

        def replace_margin(match):
            original = match.group(0)
            prop = match.group(1)
            values = match.group(2)

            fixed_values = self._fix_css_value_spacing(values, "px")

            if fixed_values != values:
                fixes.append({
                    "category": "css",
                    "type": "margin_spacing",
                    "original": original,
                    "fixed": f"{prop}:{fixed_values}"
                })
                return f"{prop}:{fixed_values}"
            return original

        pattern = r"(margin(?:-top|-right|-bottom|-left)?):([^;}'\"]+)"
        result = re.sub(pattern, replace_margin, content, flags=re.IGNORECASE)

        return result, fixes

    def _fix_css_value_spacing(self, value: str, unit: str = "px") -> str:
        """Fix spacing in CSS values like '14px0' → '14px 0'."""
        # Pattern: number followed by unit followed immediately by another number
        # E.g., "14px0" → "14px 0", "16px20px" → "16px 20px"

        # First handle cases like "14px0" (value + 0 without unit)
        value = re.sub(rf'(\d+){unit}(\d+)(?!\d|{unit})', rf'\1{unit} \2', value)

        # Then handle cases like "16px20px" (value + value)
        value = re.sub(rf'(\d+){unit}(\d+){unit}', rf'\1{unit} \2{unit}', value)

        return value

    def _fix_css_background_zero(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix background:00 → background:transparent"""
        fixes = []

        # Pattern: background:00 or background:0 0 (intended as transparent)
        def replace_bg_zero(match):
            original = match.group(0)
            prop = match.group(1)

            fixes.append({
                "category": "css",
                "type": "background_zero",
                "original": original,
                "fixed": f"{prop}:transparent"
            })
            return f"{prop}:transparent"

        # Match background:00 or background:0 0 (but not background:#00ff00)
        pattern = r"(background(?:-color)?):00?(?:\s*0)?(?![\w#])"
        result = re.sub(pattern, replace_bg_zero, content, flags=re.IGNORECASE)

        return result, fixes

    def _fix_css_border_radius(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix border-radius missing space: border-radius:6px16px → border-radius:6px 16px"""
        fixes = []

        def replace_br(match):
            original = match.group(0)
            values = match.group(1)

            fixed_values = self._fix_css_value_spacing(values, "px")

            if fixed_values != values:
                fixes.append({
                    "category": "css",
                    "type": "border_radius_spacing",
                    "original": original,
                    "fixed": f"border-radius:{fixed_values}"
                })
                return f"border-radius:{fixed_values}"
            return original

        pattern = r"border-radius:([^;}'\"]+)"
        result = re.sub(pattern, replace_br, content, flags=re.IGNORECASE)

        return result, fixes

    def _fix_js_switch_case(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix switch case missing space: case0: → case 0:"""
        fixes = []

        # Pattern: caseN: where N is a number (case0, case1, case2, etc.)
        def replace_case(match):
            original = match.group(0)
            case_num = match.group(1)

            fixes.append({
                "category": "javascript",
                "type": "switch_case_spacing",
                "original": original,
                "fixed": f"case {case_num}:"
            })
            return f"case {case_num}:"

        # Match case followed immediately by digit and colon
        # But not "case " which is already correct
        pattern = r'\bcase(\d+):'
        result = re.sub(pattern, replace_case, content)

        return result, fixes

    def _fix_js_font_declaration(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix font declaration missing space: '20052px' → '200 52px'"""
        fixes = []

        # Pattern: ctx.font = 'FONTWEIGHTFONTSIZE' where weight and size are merged
        # E.g., '20052px' should be '200 52px' (weight 200, size 52px)
        def replace_font(match):
            original = match.group(0)
            prefix = match.group(1)  # everything before the font value (e.g., "ctx.font = ")
            font_value = match.group(2)  # the font value inside quotes

            # Determine the quote type from original
            quote_char = "'" if "'" in original[len(prefix):len(prefix)+1] else '"'

            # Parse font value - look for merged weight + size
            # Common weights: 100, 200, 300, 400, 500, 600, 700, 800, 900
            font_match = re.match(r'^(100|200|300|400|500|600|700|800|900)(\d+(?:px|em|rem|pt))(.*)$', font_value)
            if font_match:
                weight = font_match.group(1)
                size = font_match.group(2)
                rest = font_match.group(3)
                fixed_value = f"{weight} {size}{rest}"

                fixes.append({
                    "category": "javascript",
                    "type": "font_declaration_spacing",
                    "original": original,
                    "fixed": f'{prefix}{quote_char}{fixed_value}{quote_char}'
                })
                return f'{prefix}{quote_char}{fixed_value}{quote_char}'
            return original

        # Match font assignments with string values
        # ctx.font = '...' or element.style.font = "..."
        # Use two separate patterns for single and double quotes
        pattern_single = r"(\.font\s*=\s*)'([^']*?)'"
        pattern_double = r'(\.font\s*=\s*)"([^"]*?)"'

        result = re.sub(pattern_single, replace_font, content)
        result = re.sub(pattern_double, replace_font, result)

        return result, fixes

    def _fix_css_generic_unit_values(self, content: str) -> Tuple[str, List[Dict]]:
        """Fix other CSS properties with missing spaces between values."""
        fixes = []

        # Properties that commonly have this issue
        properties = [
            'width', 'height', 'min-width', 'max-width', 'min-height', 'max-height',
            'top', 'right', 'bottom', 'left', 'inset',
            'gap', 'row-gap', 'column-gap',
            'translate', 'transform-origin',
        ]

        for prop in properties:
            def make_replacer(property_name):
                def replacer(match):
                    original = match.group(0)
                    values = match.group(1)

                    fixed_values = self._fix_css_value_spacing(values, "px")

                    if fixed_values != values:
                        fixes.append({
                            "category": "css",
                            "type": f"{property_name}_spacing",
                            "original": original,
                            "fixed": f"{property_name}:{fixed_values}"
                        })
                        return f"{property_name}:{fixed_values}"
                    return original
                return replacer

            pattern = rf"({prop}):([^;}}'\"]+)"
            content = re.sub(pattern, make_replacer(prop), content, flags=re.IGNORECASE)

        return content, fixes


# Singleton instance
html_fixer = HTMLFixer()


def fix_html(content: str) -> FixResult:
    """
    Convenience function to fix HTML content.

    Args:
        content: The HTML content to fix

    Returns:
        FixResult with fixed content and fix details
    """
    return html_fixer.fix(content)


def fix_html_file(file_path: str, backup: bool = True) -> FixResult:
    """
    Fix an HTML file in place.

    Args:
        file_path: Path to the HTML file
        backup: If True, create a .bak backup before modifying

    Returns:
        FixResult with fix details
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        original = f.read()

    result = html_fixer.fix(original)

    if result.has_changes:
        if backup:
            import shutil
            shutil.copy2(file_path, f"{file_path}.bak")

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(result.fixed_content)

    return result
